feat: created user authorization with login
alkemyTech/CENCO-MIT-Back-T1 pull request #4
Opened 2024-06-26 21:02 UTC by GnesisVSS

2024-06-26 21:19 UTC, Bree2003 reviewed
it seems ok

2024-06-27 00:18 UTC, LucianoFromTrelew commented on database/connection.js
> -const password = "123456";
Pueden aprovechar que utilizan un archivo `.env` para gestionar sus configuraciones y mover a ese archivo los cuatro datos que utilizan para conectar a la BD

2024-06-27 00:20 UTC, LucianoFromTrelew commented on controllers/userController.js
> +      if (!token) res.send({ massage: "El correo o la contraseña es incorrecto" })
Devolver un código de estado HTTP adecuado para esta respuesta

2024-06-27 00:30 UTC, LucianoFromTrelew requested changes
Cambios pendientes

2024-06-27 19:25 UTC, LucianoFromTrelew commented on database/connection.js
> +const database = process.env.DATABASE;
Esto está bien, pero para encontrar las configuraciones de forma más fácil pueden sacar todos los datos necesarios de `process.env` en un solo archivo (en su caso sería `config/config.js`)

2024-06-27 19:25 UTC, LucianoFromTrelew approved these changes

2024-06-27 20:00 UTC, merged