feat: feat:Gell all users from admin
alkemyTech/CENCO-MIT-Back-T1 pull request #5
Opened 2024-06-27 21:03 UTC by loonita

2024-06-27 21:18 UTC, LucianoFromTrelew commented on services/userService.js
> +  getUser: async (user) => {
Para qué utilizan este método? Si no lo usan en ningún lugar, borrenlo por favor

2024-06-27 21:21 UTC, LucianoFromTrelew commented on controllers/AdminController.js
> +import { userService } from "../services/userService.js";
Este archivo no sigue el mismo formato de nombres que el resto, debería ser `adminController.js` para ser consistente

2024-06-27 21:21 UTC, LucianoFromTrelew requested changes
Cambios pendientes

2024-06-27 22:12 UTC, LucianoFromTrelew commented on controllers/AdminController.js
> +import { userService } from "../services/userService.js";
El archivo sigue con formato incorrecto. Debería ser `adminController.js` en vez de `AdminController.js`

2024-06-27 23:00 UTC, loonita commented on services/userService.js
> +  getUser: async (user) => {
listo!

2024-06-27 23:00 UTC, loonita commented on controllers/AdminController.js
> +import { userService } from "../services/userService.js";
listo!

2024-06-27 23:04 UTC, LucianoFromTrelew commented on controllers/AdminController.js
> +import { userService } from "../services/userService.js";
Verificar los nombres de los _archivos_. Dentro de la carpeta `controllers` hay dos archivos: uno llamado `userController.js` y otro llamado `AdminController.js`. Lo que digo que es el último debería llamarse `adminController.js` para respetar la nomenclatura de nombres utilizada en todo el proyecto

2024-07-01 13:30 UTC, loonita commented on controllers/AdminController.js
> +import { userService } from "../services/userService.js";
hola, si lo había cambiado, olvide que github no detecta los cambios de mayusculas en los nombres de carpeta asi que tuve que eliminar y volver a cargar la carpeta, ahora si se muestra el cambio!

2024-07-01 13:48 UTC, LucianoFromTrelew approved these changes

2024-07-01 13:51 UTC, merged